pipeline:

  build-docker-image:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-ip-stats-ui .
    when:
      branch: master
      event: push

  test:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile_test -t pttg-ip-stats-ui-test .
      - docker run pttg-ip-stats-ui-test
    when:
      event: push

  lint:
    group: build
    image: quay.io/ukhomeofficedigital/nodejs-base:v8.11.1
    commands:
      - npm install eslint
      - npm run lint
    when:
      event: push

  install-docker-image:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:build-$${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$${DRONE_TAG}
    when:
      event: tag

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-ip-stats-ui.git
      - cd kube-pttg-ip-stats-ui && git checkout EE-16843-first-deployment-with-ingress && cd .. # TODO EE-16843 Remove once on master
    when:
      event: [push, deployment, tag]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - pttg_ip_dev
    commands:
      - cd kube-pttg-ip-stats-ui
      - ./deploy.sh
    when:
      branch: [master, EE-16843-deploy-to-dev]
      event: [push, tag]
