pipeline:

  update-semver:
    image: quay.io/ukhomeofficedigital/docker-openjdk8-git:v1.5.0
    secrets:
      - github_ssh_key
    commands:
      - sh /root/git-utilities/set-up-github-user.sh "$${GITHUB_SSH_KEY}"
      - ./gradlew release -Prelease.useAutomaticVersion=true -x runBuildTasks -s -i
      - git describe --abbrev=0 --tags > ./tagSemver
    when:
      branch: master
      event: push

  build-docker-image:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-ip-stats-ui .
    when:
      event: push

  test:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile_test -t pttg-ip-stats-ui-test .
      - docker run pttg-ip-stats-ui-test
    when:
      event: push

  lint:
    group: build
    image: quay.io/ukhomeofficedigital/nodejs-base:v8.11.1
    commands:
      - npm install eslint
      - npm run lint
    when:
      event: push

  install-docker-image-with-githash-tag:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:${DRONE_COMMIT_SHA:0:8}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:${DRONE_COMMIT_SHA:0:8}
    when:
      event: push

  install-docker-image-from-feature-branch:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:${DRONE_BRANCH}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:${DRONE_BRANCH}
    when:
      branch:
        exclude: master
      event: push

  install-docker-image-from-master-branch-build:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:latest
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:latest
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:build-$${DRONE_BUILD_NUMBER}
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$(cat ./tagSemver)
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$(cat ./tagSemver)
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$${DRONE_TAG}
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:${DRONE_COMMIT_SHA:0:8}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:${DRONE_COMMIT_SHA:0:8}
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$(cat ./tagSemver)
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$(cat ./tagSemver)
    when:
      event: tag

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-ip-stats-ui.git
      - cd kube-pttg-ip-stats-ui
      - git checkout EE-28636-fix-deployment
      - cd ..
    when:
      event: [push, deployment, tag]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - pttg_ip_dev
    commands:
      - cd kube-pttg-ip-stats-ui
      - ./deploy.sh
    when:
      branch: [master, EE-28636-fix-deployment]
      event: [push, tag]

  deployment-to-non-prod:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      - VERSION=${IMAGE_VERSION}
    secrets:
      - pttg_ip_dev
    commands:
      - cd kube-pttg-ip-stats-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, test, feat1, feat2, feat3, preprod]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - VERSION=${IMAGE_VERSION}
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
      - WHITELIST=62.25.109.196/24,52.48.127.150/32,52.48.127.151/32,52.48.127.152/32,52.48.127.153/32,52.209.62.128/25,52.56.62.128/25,185.22.224.96,185.22.224.96/32,185.22.226.96/32,213.251.23.164/32,213.251.23.185/32,213.251.23.186/32,213.251.23.187/32,52.56.62.142/24
    secrets:
      - pttg_ip_pr
    commands:
      - cd kube-pttg-ip-stats-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: pr
