pipeline:

  build-docker-image:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-ip-stats-ui .
    when:
      branch: [master, EE-16843-simple-ui] # TODO EE-16843 Make master only once happy that deployment works
      event: push

  test:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile_test -t pttg-ip-stats-ui-test .
      - docker run pttg-ip-stats-ui-test
    when:
      event: push

  lint:
    group: build
    image: quay.io/ukhomeofficedigital/nodejs-base:v8.11.1
    commands:
      - npm install eslint
      - npm run lint
    when:
      event: push

  install-docker-image:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:build-$${DRONE_BUILD_NUMBER}
    when:
      branch: [master, EE-16843-simple-ui] # TODO EE-16843 Make master only once happy that deployment works
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-stats-ui quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-stats-ui:$${DRONE_TAG}
    when:
      event: tag

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-ip-stats-ui.git
      - cd kube-pttg-ip-stats-ui && git checkout EE-16843-first-deployment-with-ingress && cd .. # TODO EE-16843 Remove once on master
    when:
      event: [push, deployment, tag]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - pttg_ip_dev
    commands:
      - cd kube-pttg-ip-stats-ui
      - ./deploy.sh
    when:
      branch: [master, EE-16843-simple-ui] # TODO EE-16843 Make master only once happy that deployment works
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - pttg_ip_dev
      - pttg_ip_test
    commands:
      - cd kube-pttg-ip-stats-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, test, preprod]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-pr
      - ENVIRONMENT=pr
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
      # - WHITELIST=62.25.109.196/32,52.48.127.150/32,52.48.127.151/32,52.48.127.152/32,52.48.127.153/32,52.209.62.128/25,52.56.62.128/25,185.22.224.96,185.22.224.96/32,185.22.226.96/32
    secrets:
      - pttg_ip_pr
    commands:
      - cd kube-pttg-ip-stats-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: pr
